### ISSUE TITLE
OSCAT.library

### ISSUE THREAD

**Issue by elconfa** [RWTH-EBC/AixOCAT#92]
## What is the issue/what feature do you want to develop?

- The last OSCAT.library was compiled on February 23, 2021, but I don't understand if it is from the "develop" branch or it is from the "master".

## What is the current application?

- The "master" branch does not have any correction or implementation listed on the "develop" branch.

## What are the requirements?

- It is not possible to compile a library from the "develop" branch, so it is easy for everyone to download and use the last library updated?

**Comment by StGoebel** [comment]
Hello @elconfa,
a new OSCAT lib file can be found in the master branch. 
Since lib files are binary, it is not possible to have an up-to-date file always in the development branch since it has to be created for every change (merge).
But you can easily create it by your own or just use the latest release from the master branch.
